#!/bin/bash -ex

mkdir build && cd build && cmake .. -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_OSX_ARCHITECTURES="$TARGET" \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_FLAGS="-O2" \
    -DCMAKE_C_FLAGS="-O2" \
    -DTORZU_ENABLE_LTO=ON \
    -DTORZU_USE_BUNDLED_VCPKG=ON \
    -DTORZU_USE_QT_WEB_ENGINE=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_HEADERS=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_SPIRV_TOOLS=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_UTILITY_LIBRARIES=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_SPIRV_TOOLS=ON \
    -DALLOW_EXTERNAL_SPIRV_TOOLS=ON \
    -DTORZU_TESTS=OFF \
    -DENABLE_WEB_SERVICE=OFF \
    -DENABLE_LIBUSB=OFF \
    -DUSE_SYSTEM_ZSTD=OFF \
    -DUSE_SYSTEM_FMT=OFF \
    -DENABLE_QT6=ON \
    -DUSE_DISCORD_PRESENCE=ON

cd build

ninja
ninja bundle

ccache -s -v

CURRENT_ARCH=`arch`
if [ "$TARGET" = "$CURRENT_ARCH" ]; then
  ctest -VV -C Release
fi
