#!/bin/sh -ex

mkdir build && cd build

cmake .. -G Ninja \
    -DBoost_INCLUDE_DIR=${BOOST_ROOT}/include \
    -DBoost_LIBRARY_DIRS=${BOOST_ROOT}/lib \
    -DBoost_COMPILER=vc143 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_FLAGS="-O2" \
    -DCMAKE_C_FLAGS="-O2" \
    -DTORZU_USE_BUNDLED_VCPKG=ON \
    -DTORZU_TESTS=OFF \
    -DTORZU_ENABLE_LTO=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_HEADERS=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_SPIRV_TOOLS=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_UTILITY_LIBRARIES=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_SPIRV_TOOLS=ON \
    -DTORZU_USE_EXTERNAL_SDL2=ON \
    -DTORZU_USE_BUNDLED_FFMPEG=OFF \
    -DALLOW_EXTERNAL_SPIRV_TOOLS=ON \
    -DUSE_DISCORD_PRESENCE=ON \
    -DUSE_SYSTEM_ZSTD=OFF \
    -DUSE_SYSTEM_FMT=OFF \
    -DENABLE_QT6=ON \
    -DENABLE_LIBUSB=ON \
    -DENABLE_WEB_SERVICE=OFF 

ninja
ninja bundle
strip -s bundle/*.exe

ccache -s -v

ctest -VV -C Release || echo "::error ::Test error occurred on Windows build"
