#!/bin/sh -ex

mkdir build && cd build && cmake .. -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -DTORZU_USE_BUNDLED_VCPKG=ON \
    -DTORZU_TESTS=OFF \
    -DTORZU_ENABLE_LTO=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_HEADERS=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_SPIRV_TOOLS=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_UTILITY_LIBRARIES=ON \
    -DTORZU_USE_EXTERNAL_VULKAN_SPIRV_TOOLS=ON \
    -DALLOW_EXTERNAL_SPIRV_TOOLS=ON \
    -DTORZU_USE_BUNDLED_QT=OFF \
    -DTORZU_USE_BUNDLED_SDL2=OFF \
    -DTORZU_USE_EXTERNAL_SDL2=ON \
    -DUSE_DISCORD_PRESENCE=ON \
    -DTORZU_USE_QT_WEB_ENGINE=ON \
    -DUSE_SYSTEM_ZSTD=OFF \
    -DUSE_SYSTEM_FMT=OFF \
    -DENABLE_WEB_SERVICE=OFF \
    -DENABLE_QT6=ON \
    -DQT_VERSION=6

ninja
ninja bundle

ccache -s -v

ctest -VV -C Release || echo "::error ::Test error occurred on Windows build"
