# SPDX-FileCopyrightText: 2022 torzu Emulator Project
# SPDX-License-Identifier: GPL-3.0-or-later

name: 'torzu-build'

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

jobs:
  Android:
    runs-on: ubuntu-24.04
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: android
      TARGET: universal
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up cache
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.ccache
          key: ${{ runner.os }}-android-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-android-
      - name: Query tag name
        uses: olegtarasov/get-tag@v2.1.3
        id: tagName
      - name: Set up JDK 22
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Install New Packages
        uses: gerlero/apt-install@v1.2.2
        with:
          packages: ccache apksigner glslang-dev glslang-tools apparmor cloud-init firefox libapparmor1 libapr1t64 libcups2t64 libopenjp2-7 libproc2-0 linux-azure linux-cloud-tools-azure linux-headers-azure linux-image-azure linux-tools-azure lxd-agent-loader mdadm nvme-cli open-vm-tools procps python3-update-manager systemd-hwe-hwdb ubuntu-pro-client ubuntu-pro-client-l10n update-manager-core php8.3 php8.3-bcmath php8.3-bz2 php8.3-cgi php8.3-cli php8.3-common php8.3-curl php8.3-dba php8.3-dev php8.3-enchant php8.3-fpm php8.3-gd php8.3-gmp php8.3-imap php8.3-interbase php8.3-intl php8.3-ldap php8.3-mbstring php8.3-mysql php8.3-odbc php8.3-opcache php8.3-pgsql php8.3-phpdbg php8.3-pspell php8.3-readline php8.3-snmp php8.3-soap php8.3-sqlite3 php8.3-sybase php8.3-tidy php8.3-xml php8.3-xsl php8.3-zip vim vim-common vim-runtime vim-tiny xxd
      - name: Update system packages
        run: |
          sudo apt-get update && sudo apt-get -y dist-upgrade && sudo apt-get clean
      - name: Build
        run: JAVA_HOME=$JAVA_HOME_22_X64 ./.ci/scripts/android/build.sh
        env:
          ANDROID_KEYSTORE_B64: ${{ secrets.DROID_KEYSTORE_B64 }}
          ANDROID_KEY_ALIAS: ${{ secrets.DROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASS: ${{ secrets.DROID_KEYSTORE_PASS }}
      - name: Copy artifacts
        run: ./.ci/scripts/android/upload.sh
      - name: Upload
        uses: actions/upload-artifact@v4.4.0
        with:
          name: android
          path: artifacts/
